using System;

namespace Terraria.Plugins.Common {
  public enum ChestStyle {
    None,
    WoodenChest,
    GoldChest,
    ShadowChest,
    Barrel,
    TrashCan,
    EbonwoodChest,
    RichMahoganyChest,
    PearlwoodChest,
    IvyChest,
    IceChest,
    LivingWoodChest,
    SkywareChest,
    ShadewoodChest,
    WebCoveredChest,
    LihzahrdChest,
    WaterChest,
    JungleChest,
    CorruptionChest,
    CrimsonChest,
    HallowedChest,
    FrozenChest,
    DynastyChest,
    HoneyChest,
    SteampunkChest,
    PalmWoodChest,
    MushroomChest,
    BorealWoodChest,
    SlimeChest,
    GreenDungeonChest,
    PinkDungeonChest,
    BlueDungeonChest,
    BoneChest,
    CactusChest,
    FleshChest,
    ObsidianChest,
    PumpkinChest,
    SpookyChest,
    GlassChest,
    MartianChest,
    MeteoriteChest,
    GraniteChest,
    MarbleChest,
    // 1.3.5
    CrystalChest,
    GoldenChest,
    // 1.4
    SpiderChest,
    LesionChest,
    DeadMansChest,
    SolarChest,
    VortexChest,
    NebulaChest,
    StardustChest,
    GolfChest,
    SandstoneChest,
    BambooChest,
    DesertChest,
  }
}
