using System;

namespace Terraria.Plugins.CoderCow {
  public enum WallType {
    Sky = 0,
    StoneWall = 1,
    DirtWall = 2,
    EbonstoneWall = 3,
    WoodWall = 4,
    GrayBrickWall = 5,
    RedBrickWall = 6,
    DungeonBlueBrickWall = 7,
    DungeonGreenBrickWall = 8,
    DungeonPinkBrickWall = 9,
    GoldWall = 10,
    SilverWall = 11,
    CopperWall = 12,
    HellstoneWall = 13,
    ObsidianBrickWall = 14,
    MudWall = 15,
    PlayerDirtWall = 16,
    BlueBrickWall = 17,
    GreenBrickWall = 18,
    PinkBrickWall = 19,
    PlayerObsidianBrickWall = 20,
    GlassWall = 21,
    PearlstoneBrickWall = 22,
    IridecentBrickWall = 23,
    MudstoneBrickWall = 24,
    CobaltBrickWall = 25,
    MythrilBrickWall = 26,
    PlankedWall = 27,
    PearlstoneWall = 28,
    CandyCaneWall = 29,
    GreenCandyCaneWall = 30,
    SnowBrickWall = 31,
  }
}
